# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/minsung/senior_project/git_works/Senior_Project/NPU/project_1/project_1.srcs/sources_1/ip/INPUT_MEM/INPUT_MEM.xci
# IP: The module: 'INPUT_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/minsung/senior_project/git_works/Senior_Project/NPU/project_1/project_1.gen/sources_1/ip/INPUT_MEM/INPUT_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INPUT_MEM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/minsung/senior_project/git_works/Senior_Project/NPU/project_1/project_1.srcs/sources_1/ip/INPUT_MEM/INPUT_MEM.xci
# IP: The module: 'INPUT_MEM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/minsung/senior_project/git_works/Senior_Project/NPU/project_1/project_1.gen/sources_1/ip/INPUT_MEM/INPUT_MEM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'INPUT_MEM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
