# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/PSUM_ROW_MEM/PSUM_ROW_MEM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PSUM_ROW_MEM || ORIG_REF_NAME==PSUM_ROW_MEM} -quiet] -quiet
