# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/WEIGHT_MEM/WEIGHT_MEM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==WEIGHT_MEM || ORIG_REF_NAME==WEIGHT_MEM} -quiet] -quiet

# IP: ip/INPUT_MEM/INPUT_MEM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==INPUT_MEM || ORIG_REF_NAME==INPUT_MEM} -quiet] -quiet
